
# dataset info
dataset_path: "/srv/home/sonic/PUPGAN/data/euvp"
mix: alternate #paired, unpaired, alternate, evolve, integer (for threshold)

# image info
chans: 3
im_width: 256
im_height: 256
num_paired: 0 #0 for full dataset

# other params
name: "alternate"
val_interval: 1 # epochs
ckpt_interval: 20  # epochs
